name: "Create Tar Release"
inputs:
  SHA:
    description: "The SHA sum of the commit"
    required: true
outputs:
  tarname:
    description: "Name of the tar file created"
    value: ${{ env.TARNAME }}
runs:
  using: "composite"
  steps:
    - run: create-tar.sh
      shell: bash
